### ISSUE TITLE
lsblk from util-linux 2.32 throws error

### ISSUE THREAD

**Issue by DennisLfromGA** [BiteDasher/brcr-update#2]
I'm using brunch on an old Acer C710 / Sandy Bridge with a rammus image:
```
User@Host  : chronos@localhost
Machine    : x86_64
Rel. name  : Chrome OS
OS Track   : stable-channel
OS Release : Linux 5.4.88-brunch-sebanc
Kernel Rel.: 5.4.88-brunch-sebanc
Brunch Ver : Brunch r87 20210124
CROS Root  : ROOT-A (/dev/sda3)
OS Board   : rammus-signed-mp-v2keys
OS Coder   : sebanc
OS Vers.   : 13597.66.0
Browser Ver: Google Chrome 88.0.4324.109
ARC Vers.  : 7073914
```
When I invoke `brcr-update` I see the error: `lsblk: unknown column: FSAVAIL`
See below for more detailed output -
```
chronos@localhost 10:33 AM [~/Downloads] $ brcr-update
lsblk: unknown column: FSAVAIL
WARNING: There is less than 5 gigabytes of free space left on your device. The installation may fail. Continue? (Enter for yes, Ctrl+C for no)

chronos@localhost 10:34 AM [~/Downloads] $ df -h ~/
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1       108G   26G   78G  25% /home/chronos/user

chronos@localhost 10:34 AM [~/Downloads] $ lsblk -V
lsblk from util-linux 2.32

chronos@localhost 10:34 AM [~/Downloads] $ lsblk -b --output FSAVAIL -z -P -n $(rootdev -d) | sed '/FSAVAIL=""/d' | cut -d '"' -f
lsblk: unknown column: FSAVAIL

```
It seems to cause the variable $all to be unset or zero and then thinks there is insufficient space available.
I don't know if anything can be done about the `util-linux` package version but I thought I'd mention it in case there was a simple remedy or workaround.

I love your updater concept, it'll save many headaches for a lot of users.

Thanx,
-**DennisLfromGA**

**Comment by BiteDasher** [comment]
Hey!  Thanks for sharing.  When I was finishing the script, I had to move from Chrome OS to Arch Linux, at that time there was a version `util-linux` 2.36.1.  Apparently, this is because of this.  As soon as I get home, I will try to rewrite the code somehow.  I have a few ideas, but unfortunately, Linux still does not have a utility that would count free space on an ENTIRE disk, not just on a specific partition.

**Comment by DennisLfromGA** [comment]
No problem, I'm not sure if others have seen this or not so maybe it's not a big issue.

I can't script my way out of a paper bag but possibly something like this might work:
- `lsblk  -po  NAME,SIZE | grep  "^$(rootdev -d)" | awk '{print $2}' | cut -d '.' -f1`

-**DennisLfromGA**

**Comment by BiteDasher** [comment]
@DennisLfromGA 
![image](https://user-images.githubusercontent.com/48867887/106476519-31f79000-64b8-11eb-8863-faf84357d819.png)

Indeed, there is no FSAVAIL column in `util-linux` 2.32. I think I'll comment out this piece of code for now. For now I'll think about how to implement it in a different way

@sebanc I hope its okay

**Comment by DennisLfromGA** [comment]
@BiteDasher,

Thanx for looking into this.

It's unfortunate that the util-linux 2.32 package does not support this. 
Maybe some kind of workaround will come to mind or an update will happen at some point.

-**DennisLfromGA**
