### ISSUE TITLE
update script work with unstable brunch?

### ISSUE THREAD

**Issue by madhits** [BiteDasher/brcr-update#3]
So currently I have brunch unstable r88 installed but chrome os is on r87. It appears your script must update brunch first. Is there a way to tell it to update chrome os and slip the brunch update? Or does your script not work with the unstable channel? If not why?

I ran it anyway and switched to stable channel but perhaps you can add the option.

**Comment by BiteDasher** [comment]
This script is made for ordinary users who update the OS as soon as identical versions of `brunch` and `ChromeOS` are released. If you want to update the `ChromeOS` and then `brunch`, use `chromeos-update`
