### ISSUE TITLE
unzip binary

### ISSUE THREAD

**Issue by TaiPhamD** [BiteDasher/brcr-update#4]
Could you please provide the source of the unzip binary? I feel a bit uneasy running binary without knowing its source. Thank you.

**Comment by BiteDasher** [comment]
I take it from https://downloads.sourceforge.net/project/infozip/UnZip%206.x%20%28latest%29/UnZip%206.0/unzip60.tar.gz

> Could you please provide the source of the unzip binary? I feel a bit uneasy running binary without knowing its source. Thank you.

**Comment by BiteDasher** [comment]
Or, from Debian Buster repository. Nothing bad here, you can replace this if you want
