### ISSUE TITLE
Your script will update even when support has stopped.

### ISSUE THREAD

**Issue by madhits** [BiteDasher/brcr-update#5]
Hello, 
I have a samus install and saw that r91 was out. I was on r90 which i did not know was the final for samus. So I went ahead and updated. Install went fine but I get constant crashes. What i cant figure out is which r91 did it attempt to install since there is no r91 for samus. Your script kept saying it was on r91 and about chrome said it was r90. So I guess using latest brunch with r90 is what is causing the issues. Anyway I wonder if you can add a check to confirm that the recovery and brunch match, to stop this in the future. Also love to see a downgrade option.

**Comment by Miustone** [comment]
Talking about Downgrades. I would also love to see support for more Update Channels like Beta and Dev besides the Stable One. Thanks anyways for the nice Script BiteDasher!

**Comment by BiteDasher** [comment]
> Hello, 
> I have a samus install and saw that r91 was out. I was on r90 which i did not know was the final for samus. So I went ahead and updated. Install went fine but I get constant crashes. What i cant figure out is which r91 did it attempt to install since there is no r91 for samus. Your script kept saying it was on r91 and about chrome said it was r90. So I guess using latest brunch with r90 is what is causing the issues. Anyway I wonder if you can add a check to confirm that the recovery and brunch match, to stop this in the future. Also love to see a downgrade option.

I don't have the time to finalize the script right now.  Including the implementation of a check on the latest available version of Chrome OS and the corresponding brunch version is quite difficult.  I would advise you to just look at the numbers output by the script and decide whether to update or not.  Someday, I think I'll do it.  But at the expense of downgrade the version, I'm not sure if this is the main task of the script. If you can modify the script yourself, send me a pull request.

**Comment by BiteDasher** [comment]
The link for Chrome OS updates that I am parsing does not contain information about the version of the browser.  Build number only.  So at the moment I don't know how to get the latest version just by parsing the cros-updates website, but it often doesn't respond.  When updating, always match the Chrome OS build on cros-updates and the brunch version, until I figure out what to do

**Comment by BiteDasher** [comment]
@madhits I think it's solved now. Try to update and please write whether there were any errors during the execution of the script
