### ISSUE TITLE
downloading previous build of Brunch

### ISSUE THREAD

**Issue by darren3** [BiteDasher/brcr-update#7]
When I run your script a previous copy of brunch starts to download, I currently have Brunch r91 stable 20210620 installed. I have attached a screenshot.

![Screenshot 2021-07-30 16 27 15](https://user-images.githubusercontent.com/5213196/127676436-026fe7e4-7967-45d5-aecc-dd1970abcbee.png)

**Comment by BiteDasher** [comment]
@darren3 brcr fetches brunch version based on current available Chrome OS recovery image. Currently I have no plans to change this behaviour. Maybe sometimes I will change this

**Comment by darren3** [comment]
thanks
